name: CI
on:
  workflow_dispatch:
  # Triggers the workflow on push or pull request events but only for the main branch
  # schedule:
    # - cron:  '0 0,6,12,18 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3


